change dockerfile fe

diff --git a/electronic-e-commerce/Dockerfile b/electronic-e-commerce/Dockerfile
--- a/electronic-e-commerce/Dockerfile
+++ b/electronic-e-commerce/Dockerfile
@@ -35,6 +35,12 @@ ARG VITE_BACKEND_API_URL
 ARG VITE_GOOGLE_CLIENT_ID
 ARG VITE_GOOGLE_REDIRECT_URI
 
+RUN if [ -z "$VITE_BACKEND_API_URL" ] || \
+    [ -z "$VITE_GOOGLE_CLIENT_ID" ] || \
+    [ -z "$VITE_GOOGLE_REDIRECT_URI" ]; then \
+    echo "❌ Missing required VITE environment variables" && exit 1; \
+    fi
+
 ENV VITE_BACKEND_API_URL=$VITE_BACKEND_API_URL
 ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
 ENV VITE_GOOGLE_REDIRECT_URI=$VITE_GOOGLE_REDIRECT_URI
